version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: sensor_user
      POSTGRES_PASSWORD: sensor_pass
      POSTGRES_DB: sensor_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    env_file: .env
    depends_on:
      - db
    ports:
      - "8000:8000"

  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    env_file: .env
    depends_on:
      - api
    ports:
      - "8501:8501"

volumes:
  pgdata:

